{
 "title": "Containers",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"spark\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_memory_usage_bytes{name=\"spark_worker\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_memory_usage_bytes{name=\"airflow_scheduler\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"airflow_scheduler\"}[1m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"spark\"}[1m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"spark_worker\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "No. containers Running",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(container_tasks_state{state=\"running\", name!=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}